### ISSUE TITLE
Dark font in status bar

### ISSUE THREAD

**Issue by kv4sha** [primer/github-vscode-theme#35] opened 2020-05-14 11:22 UTC
Hi! Cool theme =)

Too dark font in Status Bar in debug mode in dark version of the theme.

<img width="509" alt="Screen Shot 2020-05-14 at 14 11 12" src="https://user-images.githubusercontent.com/13916346/81928676-5049f280-95ee-11ea-9221-e498f141c62a.png">

**Comment by this-fifo** [comment] 2020-05-14 15:09
I think this might be a duplicate of #34 which was recently addressed

**Comment by jonrohan** [comment] 2020-05-14 19:47
Closing as duplicate, thanks @kv4sha and @this-fifo

**Closed by jonrohan** 2020-05-14 19:47 UTC
