### ISSUE TITLE
Fix dart code theme in new update

### ISSUE THREAD

**Issue by aminsamad** [primer/github-vscode-theme#192] opened 2021-08-02 21:07 UTC

**Comment by dominicegginton** [comment] 2021-08-03 10:08
Thanks for opening an issue. Can you add more information?
- What needs fixing?
- Provide any screenshots if necessary?
- Maybe suggest a solution?

**Comment by aminsamad** [comment] 2021-08-04 19:06
![Screenshot 2021-08-04 220338](https://user-images.githubusercontent.com/73881942/128239904-71ea583d-6b7c-4449-bf45-1f39776db775.jpg)
Almost all colors code are orange, but before the update it wasn't like that it changed after the latest dart code update

**Comment by dominicegginton** [comment] 2021-08-04 23:26
I can not seem to replicate the syntax highlighting you are having. Do you have any other VSCode extensions enabled that change the color theme.

**Comment by mitulvaghamshi** [comment] 2021-08-05 15:51
I have the same issue (Aug 4th), disabling **Dart** and **Flutter** plugins and reloading vs code will resolve this orange issue for me. But it's not the right solution and the problem is with Dart plugin. If anyone can confirm this as well.

**Comment by dominicegginton** [comment] 2021-08-05 17:06
I can confirm that this is an issue with the **Dark** and/or **Flutter** plugin. @aminsamad you can close this issue. Please report the issue to the appropriate VSCode extension devs 😄

**Closed** 2021-08-06 19:52 UTC

**Comment by albertms10** [comment] 2021-08-22 11:49
Has this been issued to Dart or Flutter-related plugins’ already? It works fine with VSCode’s **Light+** and **Dark+** variants, and only appears to be happening with GitHub’s theme.

![vscode-dart-github-theme](https://user-images.githubusercontent.com/26429103/130353924-a5ccb512-154a-4d9c-b92f-c041a57f9279.gif)

**Comment by dominicegginton** [comment] 2021-08-24 10:08
@albertms10 I will take a look into this. However, I am not a dark/flutter dev so don't use the tooling around the ecosystem. Could you please leave a list of installed VSCode extensions:

``` shell
$ code --list-extensions | xargs -L 1 echo code --install-extension

```

**Comment by albertms10** [comment] 2021-08-24 10:38
You can reproduce the undesired situation by leaving VSCode with at least both **GitHub Theme** and **Dart** extensions:

```bash
$ code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension Dart-Code.dart-code
code --install-extension GitHub.github-vscode-theme
```

<div style="display: flex">
  <img src="https://user-images.githubusercontent.com/26429103/130602348-9ddd3055-b8bd-42a2-be31-cbec0818dc43.png" width="400">
  <img src="https://user-images.githubusercontent.com/26429103/130602336-1222cd80-3e35-427c-b6db-95a7b01ca3f2.png" width="400">
</div>

**Comment by mitulvaghamshi** [comment] 2021-08-24 16:01
https://user-images.githubusercontent.com/52579416/130649955-7d56e6a0-f1b0-4396-a5e5-5dabe69c0c9f.mov

Disabling semantic highlighting as:  ```"editor.semanticHighlighting.enabled": false``` will make things working...

**Comment by albertms10** [comment] 2021-09-02 07:47
Right, disabling semantic highlighting makes it work fine. So, it seems to be related to this PR, maybe:
- https://github.com/Dart-Code/Dart-Code/issues/2202

**Comment by zs-dima** [comment] 2022-11-30 20:21
@albertms10 Issue still there and 'Disabling semantic highlighting' is not a good solution as highlighting became less helpful.
Is there any solution to fix this issue? Maybe open this issue again?
