### ISSUE TITLE
Selected text at the top of a collapsed block loses its highlight colour

### ISSUE THREAD

**Issue by stellirin** [primer/github-vscode-theme#131] opened 2021-02-02 11:24 UTC
I see this most often in larger files when I collapse a bunch of code blocks then try to select (part of) the function name that is still visible. It is not clear if I have selected any text unless I see the same string nearby.

Other themes do not have this issue.

GitHub Light
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1012095/106593256-dfb67d80-6550-11eb-83e6-b2edbb5c16e2.png">

GitHub Dark
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1012095/106593208-d0cfcb00-6550-11eb-97a9-ae8cd697b3b9.png">

Dark (Visual Studio):
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1012095/106593674-653a2d80-6551-11eb-8e6c-bb6ac5322f5d.png">

High Contrast:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1012095/106593100-aa119480-6550-11eb-86f5-ad2af4825edb.png">

**Comment by simurai** [comment] 2021-03-27 02:21
@stellirin Thanks for reporting. 🙇  I'll close this as duplicate of #53.

You might also wanna take a look at this workaround https://github.com/primer/github-vscode-theme/issues/53#issuecomment-808325859 pointed out by @kevinfarrugia.

**Closed by simurai** 2021-03-27 02:21 UTC
