### ISSUE TITLE
Alt+F8 window

### ISSUE THREAD

**Issue by orsenkucher** [primer/github-vscode-theme#52] opened 2020-05-30 22:14 UTC
vscode has this error/warning window, you can open it with `alt`+`F8`
![image](https://user-images.githubusercontent.com/15790628/83339986-e0b95000-a2db-11ea-9660-d6aab76f894b.png)

**Comment by simurai** [comment] 2023-01-05 05:46
This seems to work as intended? Gonna close this again since I'm not sure what the issue is. Feel free to re-open with more details.

**Closed by simurai** 2023-01-05 05:46 UTC
