### ISSUE TITLE
Problem with selection in diff

### ISSUE THREAD

**Issue by bmarvinb** [primer/github-vscode-theme#273] opened 2022-04-04 05:26 UTC
When I select text in diff editor, it doesn't change any color of what I select

Here is example, where I selected "Welcome"
![image](https://user-images.githubusercontent.com/23120972/161479362-6475072a-e889-4af9-81b5-53e8ae4c36d5.png)

And how it looks in default theme
![image](https://user-images.githubusercontent.com/23120972/161479395-c4b989bd-766d-474c-9645-31b13557dbb1.png)

**Comment by kolibril13** [comment] 2022-05-02 05:49
Same here (Theme: "Github Light Default"):

https://user-images.githubusercontent.com/44469195/166190061-06dffd45-cccb-47aa-b40e-9b883d64059f.mov

The Problem does not occur with the "Github Light" theme. 
Also, "Github Dark" and "Github Dark Default" don't have this problem.

**Comment by zepfietje** [comment] 2022-05-17 10:39
I believe this is a duplicate of https://github.com/primer/github-vscode-theme/issues/223. If so, could you close this issue and support the other thread?

**Closed** 2022-05-17 12:20 UTC
