### ISSUE TITLE
Inline style semicolon is not the same

### ISSUE THREAD

**Issue by leechaojie** [primer/github-vscode-theme#163] opened 2021-04-22 09:41 UTC
![image](https://user-images.githubusercontent.com/28593271/115692801-e3a8ad80-a391-11eb-9473-5c643c253b0a.png)

**Comment by manniL** [comment] 2022-05-10 19:57
![grafik](https://user-images.githubusercontent.com/640208/167711656-dc2c2184-9f46-4c86-bbe0-4376e65e832a.png)
This should be fixed in the meantime ☺️

**Comment by simurai** [comment] 2022-07-15 08:29
> This should be fixed in the meantime

Yes, I also can't reproduce it anymore:

![image](https://user-images.githubusercontent.com/378023/179184819-15bf14e2-ff3b-4e44-b24d-9522cec0b9a2.png)

**Closed by simurai** 2022-07-15 08:29 UTC
