### ISSUE TITLE
All Dark Color Font / Text when using Github Dark with Source Code Pro

### ISSUE THREAD

**Issue by SharkIng** [primer/github-vscode-theme#71] opened 2020-07-14 19:06 UTC
![image](https://user-images.githubusercontent.com/3316062/87465703-1ba0ea00-c5e3-11ea-9fbd-eabd8205fd6b.png)

Please see attached screenshot. 

I don't know if it's a known issue, done in purposes or it's a bug. Also I didn't try other font family.
As showing on the screenshot, when set font Family Source Code Pro, all text become dark black. Remove `fontFamily` fix the problem

OS: MacOS Big Sur
VS Code: Version: 1.47.1

**Comment by Paquan** [comment] 2020-11-13 13:07
@SharkIng 

Today I ran in the same issue since I've updated my macOS to Big Sur but with every theme. So thank you for the hint with the Font, I was wondering why nobody complains about broken style.

**Comment by ernestyao** [comment] 2020-11-14 11:08
Yeah, I ran in to the same issue after updating to Big Sur.

**Comment by EivindB** [comment] 2020-11-15 17:53
Ran into the issue with both, VSCode, Hyper, Firefox and Chrome - but not in Safari. So it's perhaps an issue with the web engines of these apps in combination with the font?

![Screenshot 2020-11-15 at 18 50 26](https://user-images.githubusercontent.com/111363/99192523-946fa880-2773-11eb-9c27-a3743e14c15b.png)
Safari top left, Chrome Top Right, Hyper bottom left, Firefox bottom right
Website viewed is [this](https://scotch.io/tutorials/best-packages-and-themes-for-hyper-the-terminal-built-on-web-technologies) which uses Source Code Pro for its code blocks.

**Comment by manngo** [comment] 2020-11-17 06:38
I had the same problem with Atom and Firefox. The problem is with `Source Code Pro`:

https://github.com/adobe-fonts/source-code-pro/issues/250

Fortunately, there is a fixed version available.

**Comment by SharkIng** [comment] 2020-11-17 22:28
@EivindB Apparently I don't have any issue with the latest MacOS + the latest Chrome. Firefox Developer Edition on my Macbook also works fine at the moment.

I've stop using source code pro on my VS Code so I don't know if they fixed it or not.

**Comment by simurai** [comment] 2022-07-15 06:39
Gonna close this since it sounds to be more a problem with the actual font.

**Closed by simurai** 2022-07-15 06:39 UTC
